version: '3.1'

services:
  auth-db:
    image: mysql:latest
    restart: always
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_auth:/var/lib/mysql

  course-db:
    image: mysql:latest
    restart: always
    container_name: course-db
    env_file:
      - ./backend/CourseManagementService/.env
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_course:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  # Health check command
      timeout: 10s
      retries: 5
      interval: 5s

  notification-db:
    image: mongo:latest
    restart: always
    container_name: notification-db
    ports:
      - "27017"
    env_file:
      - ./backend/NotificationService/.env

  auth-service:
    build:
      context: ./backend/AuthenticationService
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    depends_on:
      - auth-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://auth-db:3306/auth
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8082"

  course-service:
    build:
      context: ./backend/CourseManagementService
      dockerfile: Dockerfile
    container_name: course-service
    ports:
      - "5000:5000"
    env_file:
      - ./backend/CourseManagementService/.env
    depends_on:
      course-db:
        condition: service_healthy

  notification-service:
    build:
      context: ./backend/NotificationService
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "4000:4000"
    env_file:
      - ./backend/NotificationService/.env
    depends_on:
      - notification-db
      
  studystorm-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: studystorm-app
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env

volumes:
  mysql_data_auth:
  mysql_data_course:
